### ISSUE TITLE
PATCH/POST Dimensions API

### ISSUE THREAD

**Issue by jkm-blue** [AdobeDocs/cja-apis#176]
### Expected Behaviour
Ability to update dimensional settings within a dataview.

### Actual Behaviour
Only option is through UI or non-public API.

### Reproduce Scenario (including but not limited to)
API reference documentation only has GET requests for the Dimensions API.

#### Steps to Reproduce
[link](https://developer.adobe.com/cja-apis/docs/api/#tag/Dimensions-API)

**Comment by stewartschillingsdi** [comment]
+1 on this.  It sure would be nice to have an endpoint for PUT and POST.

**Comment by lukkyluke** [comment]
+1, and also on metrics

**Comment by johnwight** [comment]
Thank you for submitting this issue. I will pass this along to the developers and once we have a public endpoint for this, I will make sure it gets documented.

**Comment by johnwight** [comment]
I am going to re-open this and send it to PM as is. I will create a ticket for this for PMs. I know this has been discussed much, but not sure if a github issue has been cited like this. So I will leave it open and cite it for PMs to make sure they know about the request. This is the documentation repo and I only work in documentation so I cannot provide any development or product assurances. But I will do my best to make sure your expressions here get passed along.

**Comment by johnwight** [comment]
I have put in a ticket for this API request. I will leave this open so PMs can refer to it. Also, I found out that API feature requests can also be submitted here: https://experienceleaguecommunities.adobe.com/t5/adobe-analytics-ideas/idb-p/adobe-analytics-ideas.

**Comment by johnwight** [comment]
This feature is being regularly requested by product team but since it is not strictly a documentation issue, I am closing this.
