### ISSUE TITLE
Create dataview - not setting owner properly

### ISSUE THREAD

**Issue by lukkyluke** [AdobeDocs/cja-apis#328]
## URL of documentation issue
https://developer.adobe.com/cja-apis/docs/api/#tag/Dataviews-API/operation/createDataView

## Description
When creating a dataview through CJA API the owner property is not set to the specified one in the request body.
Instead the owner seems to be set to the account that is used for authorization against the API.
However, PUT /data/dataviews/:dataViewId?expansion=name,owner with a specified owner in the request body works fine. 

Steps for reproducing:
POST /data/dataviews?expansion=name,owner
with a defined owner (other than the account used for auth against the api) in the request body.
The owner is set to the account used for auth against the API

**Comment by johnwight** [comment]
Thank you for submitting this issue. I will tag a developer to see if this is intended behavior. If so, I will update the documentation.

**Comment by johnwight** [comment]
Hi @lukkyluke, Response from developer: "The owner used in the body is overridden by the user making the request. We don't allow a user to create a dataview for someone else. (We have other unexposed endpoints for that.)" I hope that helps. Thanks for using the API services.

**Comment by johnwight** [comment]
The behavior of this issue has been clarified in the following documentation:

https://developer.adobe.com/cja-apis/docs/endpoints/dataviews/

"Note that the owner in the body is overridden by the user making the request."

**Comment by lukkyluke** [comment]
Sorry, I don't understand. 
So why is owner a request parameter on that endpoint?
