### ISSUE TITLE
Bad links on "Resources" menu

### ISSUE THREAD

**Issue by JMiller-Disco** [AdobeDocs/cja-apis#47]
### Expected Behaviour
Linked to appropriate page. In this case, the API Reference should link to the following address: https://www.adobe.io/cja-apis/docs/api/

### Actual Behaviour
When you click on "API References" it takes the user to the following address: https://www.adobe.io/cja-apis/docs/39b49e28d2b66eac51403e1480923fd7/api.md

#### Steps to Reproduce
Navigate to the main CJA API page, https://www.adobe.io/cja-apis/docs/ . Using the Resources menu, click the "API References" link.

**Comment by Titikorn555** [comment]
> ### Expected Behaviour
> Linked to appropriate page. In this case, the API Reference should link to the following address: https://www.adobe.io/cja-apis/docs/api/
> 
> ### Actual Behaviour
> When you click on "API References" it takes the user to the following address: https://www.adobe.io/cja-apis/docs/39b49e28d2b66eac51403e1480923fd7/api.md
> 
> ### Reproduce Scenario (including but not limited to)
> #### Steps to Reproduce
> Navigate to the main CJA API page, https://www.adobe.io/cja-apis/docs/ . Using the Resources menu, click the "API References" link.
> 
> #### Platform and Version
> #### Sample Code that illustrates the problem
> #### Logs taken while reproducing problem

BUybuydadmomsexandnxe.gtsking10andtamethai...off bankgsbthailand backkingcobba

**Comment by gigazelle** [comment]
Hi @JMiller-Disco - This issue appears to be fixed. Please reopen it and let me know if you're still seeing issues!
